export const CHANGE_STATE_ROUTING_0 = 'CHANGE_STATE_ROUTING_0';
export const CHANGE_STATE_ROUTING_1 = 'CHANGE_STATE_ROUTING_1';
export const CHANGE_STATE_ROUTING_2 = 'CHANGE_STATE_ROUTING_2';
export const CHANGE_STATE_ROUTING_3 = 'CHANGE_STATE_ROUTING_3';

export const CHANGE_STATE_PAGES_RESET = 'CHANGE_STATE_PAGES_RESET';
export const CHANGE_STATE_PAGES_0 = 'CHANGE_STATE_PAGES_0';
export const CHANGE_STATE_PAGES_1 = 'CHANGE_STATE_PAGES_1';
export const CHANGE_STATE_PAGES_2 = 'CHANGE_STATE_PAGES_2';
export const CHANGE_STATE_PAGES_3 = 'CHANGE_STATE_PAGES_3';

export const RESET_BOOKING = 'RESET_BOOKING';

export const CHANGE_VERIFICATION = 'CHANGE_VERIFICATION';

export const GET_CITIES_DATA = 'GET_CITIES_DATA';
export const LOADING_CITIES_DATA = 'LOADING_CITIES_DATA';

export const GET_CARS_DATA = 'GET_CARS_DATA';
export const LOADING_CARS_DATA = 'LOADING_CARS_DATA';

export const GET_POINTS_DATA = 'GET_POINTS_DATA';
export const LOADING_POINTS_DATA = 'LOADING_POINTS_DATA';
export const RESET_POINTS_DATA = 'RESET_POINTS_DATA';

export const GET_RATES_DATA = 'GET_RATES_DATA';
export const LOADING_RATES_DATA = 'LOADING_RATES_DATA';

export const GET_CATEGORIES_DATA = 'GET_CATEGORIES_DATA';
export const LOADING_CATEGORIES_DATA = 'LOADING_CATEGORIES_DATA';

export const CHANGE_TICKET = 'CHANGE_TICKET';
export const RESET_TICKET = 'RESET_TICKET';

export const GET_ORDER_DATA = 'GET_ORDER_DATA';
export const LOADING_ORDER_DATA = 'LOADING_ORDER_DATA';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const ERROR_ORDER_DATA = 'ERROR_ORDER_DATA';
export const RESET_ORDER_DATA = 'RESET_ORDER_DATA';

export const GET_DRAFT_DATA = 'GET_DRAFT_DATA';

export const POST_LOGIN = 'POST_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const RESET_LOGIN = 'RESET_LOGIN';
export const POST_LOGOUT = 'POST_LOGOUT';
export const POST_REGISTER = 'POST_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';
export const POST_REFRESH = 'POST_REFRESH';
export const ERROR_REFRESH = 'ERROR_REFRESH';

export const GET_ORDERS_DATA = 'GET_ORDERS_DATA';
export const LOADING_ORDERS_DATA = 'LOADING_ORDERS_DATA';
export const ERROR_ORDERS_DATA = 'ERROR_ORDERS_DATA';

export const GET_FILTER_MODELS = 'GET_FILTER_MODELS';
export const GET_FILTER_CITIES = 'GET_FILTER_CITIES';
export const GET_FILTER_STATUS = 'GET_FILTER_STATUS';
