export const CHANGE_STATE_ROUTING_0 = 'CHANGE_STATE_ROUTING_0';
export const CHANGE_STATE_ROUTING_1 = 'CHANGE_STATE_ROUTING_1';
export const CHANGE_STATE_ROUTING_2 = 'CHANGE_STATE_ROUTING_2';
export const CHANGE_STATE_ROUTING_3 = 'CHANGE_STATE_ROUTING_3';

export const CHANGE_STATE_PAGES_RESET = 'CHANGE_STATE_PAGES_RESET';
export const CHANGE_STATE_PAGES_0 = 'CHANGE_STATE_PAGES_0';
export const CHANGE_STATE_PAGES_1 = 'CHANGE_STATE_PAGES_1';
export const CHANGE_STATE_PAGES_2 = 'CHANGE_STATE_PAGES_2';
export const CHANGE_STATE_PAGES_3 = 'CHANGE_STATE_PAGES_3';

export const GET_CITIES_DATA = 'GET_CITIES_DATA';
export const LOADING_CITIES_DATA = 'LOADING_CITIES_DATA';

export const GET_CARS_DATA = 'GET_CARS_DATA';
export const LOADING_CARS_DATA = 'LOADING_CARS_DATA';

export const GET_POINTS_DATA = 'GET_POINTS_DATA';
export const LOADING_POINTS_DATA = 'LOADING_POINTS_DATA';
export const RESET_POINTS_DATA = 'RESET_POINTS_DATA';

export const GET_RATES_DATA = 'GET_RATES_DATA';
export const LOADING_RATES_DATA = 'LOADING_RATES_DATA';

export const GET_CATEGORIES_DATA = 'GET_CATEGORIES_DATA';
export const LOADING_CATEGORIES_DATA = 'LOADING_CATEGORIES_DATA';

export const CHANGE_TICKET = 'CHANGE_TICKET';

export const GET_DRAFT_DATA = 'GET_DRAFT_DATA';
